# Generated by Django 5.0.6 on 2024-05-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='event_des',
            new_name='medicine_des',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='eventdate',
            new_name='medicinedate',
        ),
        migrations.RenameField(
            model_name='videogallery',
            old_name='event_des',
            new_name='medicine_des',
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=200, null=True)),
                ('medicine_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('speaker_picture', models.ImageField(null=True, upload_to='static/speaker')),
                ('price', models.IntegerField()),
                ('dprice', models.IntegerField()),
                ('medicine_date', models.DateField()),
                ('medicine_detail', models.TextField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.city')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.placename')),
                ('medicine_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.DeleteModel(
            name='event',
        ),
    ]
