# Generated by Django 5.0.6 on 2024-05-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_hotel_medicine_shop_alter_placename_ppic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placename',
            name='ppic',
            field=models.ImageField(null=True, upload_to='static/shop/'),
        ),
    ]
